type ReadInput = () => Promise<string>;

type AgentAddFields = {
  acknowledgementPointer?: string;
  acknowledgementValues?: readonly string[];
  agentId: string;
  argvJson?: string;
  attemptTimeout?: string;
  backgroundCommand?: string;
  bridgeConcurrency?: 'serial' | 'multiplexed';
  cancellationGrace?: string;
  closeTimeout?: string;
  connectionMode?: 'serial' | 'multiplexed';
  cwd?: string;
  env?: readonly string[];
  errorPointer?: string;
  eventName?: string;
  headerEnv?: readonly string[];
  incrementalOutputMode?: 'text' | 'array';
  incrementalOutputPointer?: string;
  idleTimeout?: string;
  invokeUrl?: string;
  jsonlCommand?: string;
  name?: string;
  nativeCommand?: string;
  nativeHttp?: string;
  openTimeout?: string;
  pingInterval?: string;
  readinessHttp?: string;
  readinessStderr?: string;
  readinessTcp?: string;
  requestIdPointer?: string;
  requestTemplate?: string;
  responsePointer?: string;
  shutdownUrl?: string;
  stopTimeout?: string;
  streamFraming?: 'sse' | 'jsonl';
  streamUrl?: string;
  terminalPointer?: string;
  terminalValues?: readonly string[];
  timeout?: string;
  trace?: boolean;
  tracePointer?: string;
  webSocketLifecycle?: 'per_case' | 'per_run';
  webSocketSubprotocol?: string;
  webSocketUrl?: string;
};

export { type AgentAddFields, type ReadInput };
