/** Public core runtime APIs (PLAN Phase 1): run store + run diffing. */
export {
  BUNDLE_VERSION,
  StoreError,
  exportRunBundle,
  openRunStore,
  openStore,
  readRunBundle,
  type AttestStore,
  type BundleCase,
  type BundleFooter,
  type BundleHeader,
  type BundleLine,
  type BundleManifest,
  type CacheKind,
  type CacheStore,
  type CaseOutcome,
  type CaseRecord,
  type CaseSummary,
  type InvocationError,
  type RunMetadata,
  type RunRecord,
  type RunStatus,
  type RunStore,
  type RunSummary,
  type StoredAttempt,
  type StoredCaseExecution,
  type StoredDiagnostics,
  type StoredInvocationErrorCode,
  type StoredMetricEvaluation,
} from './store/index.js';
export {
  DiffConfigError,
  classifyRuns,
  classifyTransition,
  computeCaseVerdict,
  computeMetricDeltas,
  diffRuns,
  diffToJson,
  evaluateThresholds,
  runToJUnitXml,
  type CaseTransition,
  type CaseTransitionKind,
  type CaseVerdict,
  type CiVerdict,
  type DiffSummary,
  type MetricDelta,
  type RunDiff,
  type ThresholdConfig,
} from './diff/index.js';
