CREATE TABLE runs (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, finished_at TEXT, status TEXT NOT NULL CHECK (status IN ('running','completed','failed','cancelled')), config_version TEXT NOT NULL, config_hash TEXT NOT NULL, config_json TEXT NOT NULL, git_sha TEXT, git_branch TEXT, labels_json TEXT, summary_json TEXT);
CREATE TABLE cases (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, case_id TEXT NOT NULL, suite_name TEXT NOT NULL, outcome TEXT NOT NULL CHECK (outcome IN ('completed','invocation_error','timeout','cancelled')), started_at TEXT NOT NULL, duration_ms INTEGER NOT NULL, input_hash TEXT NOT NULL, request_json TEXT NOT NULL, response_json TEXT, response_warnings_json TEXT, invocation_error_json TEXT, trace_json TEXT, UNIQUE (run_id, suite_name, case_id));
CREATE TABLE metric_results (id TEXT PRIMARY KEY, case_row_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE, metric_name TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('assertion','exec','judge')), status TEXT NOT NULL CHECK (status IN ('evaluated','error')), score REAL, pass INTEGER, rationale TEXT, details_json TEXT, error_json TEXT, judge_io_json TEXT, duration_ms INTEGER, UNIQUE (case_row_id, metric_name));
CREATE TABLE spans (id TEXT PRIMARY KEY, case_row_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE, span_id TEXT NOT NULL, parent_span_id TEXT, kind TEXT NOT NULL, name TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, status TEXT, tool_name TEXT, model_name TEXT, UNIQUE (case_row_id, span_id));
CREATE TABLE response_cache (cache_key TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('agent','judge')), payload_json TEXT NOT NULL, created_at TEXT NOT NULL, last_used_at TEXT NOT NULL, PRIMARY KEY (kind, cache_key));
CREATE INDEX idx_cases_run ON cases(run_id);
CREATE INDEX idx_metric_results_case ON metric_results(case_row_id);
CREATE INDEX idx_spans_case ON spans(case_row_id);
CREATE INDEX idx_runs_created ON runs(created_at DESC);
