/** Limits applied when an agent resource leaves the corresponding timeout or cap unset. */
const DEFAULT_ATTEMPT_MS = 60_000;
const DEFAULT_CONNECT_MS = 10_000;
const DEFAULT_FIRST_BYTE_MS = 30_000;
const DEFAULT_IDLE_MS = 30_000;
const DEFAULT_REQUEST_BYTES = 10 * 1024 * 1024;
const DEFAULT_RESPONSE_BYTES = 10 * 1024 * 1024;
const DEFAULT_EVENT_COUNT = 10_000;
const DEFAULT_EVENT_BYTES = 1024 * 1024;
const DEFAULT_TOTAL_EVIDENCE_BYTES = 10 * 1024 * 1024;
const DEFAULT_STDERR_BYTES = 16 * 1024;
const DEFAULT_TERMINATION_GRACE_MS = 5_000;

export {
  DEFAULT_ATTEMPT_MS,
  DEFAULT_CONNECT_MS,
  DEFAULT_EVENT_BYTES,
  DEFAULT_EVENT_COUNT,
  DEFAULT_FIRST_BYTE_MS,
  DEFAULT_IDLE_MS,
  DEFAULT_REQUEST_BYTES,
  DEFAULT_RESPONSE_BYTES,
  DEFAULT_STDERR_BYTES,
  DEFAULT_TERMINATION_GRACE_MS,
  DEFAULT_TOTAL_EVIDENCE_BYTES,
};
